### ISSUE TITLE
I made a UI interface for "Keylogger",  but it didn't work ...

### ISSUE THREAD

**Issue by DamonGG** [SkrewEverything/Swift-Keylogger#14]
@SkrewEverything 
First of all, thanks a lot for your great project.

I want to control the keyboard listening events with a switch Button. So I made a UI interface wrap it (use Xcode). I copy your codes into my project and create a view controller. Then I add a action for a checkbox Button :
```
 @IBAction func buttonFieldChecked(_ sender: NSButton) {
        let state = sender.state
        if state == .on {
            _ = Keylogger()  // if checked, listen the keyboard pressing
        } else {
            //...
        }
    }
```
But when I run and checked button, the UI application hanging and the mouse pointer loading forever.

I guess the reason in "Keylogger.swift":
```
       /* Scheduling the loop */
        scheduleHIDLoop()
       
        /* Running in Loop */
        RunLoop.current.run()
```
But I don't know how to fix it. Could you give me some advice? Thank you very much!  : )

**Comment by SkrewEverything** [comment]
@DamonGG Your guess is correct.

`RunLoop.current.run()` is used to run the keylogger while using as an executable or from command line(and this is how the keylogger is created for).

You can read my answer on SO as to why your mouse pointer is loading forever: https://stackoverflow.com/questions/41755575/run-a-thread-continuously-without-blocking-main-thread-in-swift/46846702#46846702

To run it from your UI app, you have to modify the source code.

**Step: 1**
Comment out these lines in **`Keylogger.swift`** -> **`init()`**
<img width="540" alt="screen_shot_2018-07-05_at_6_33_22_pm" src="https://user-images.githubusercontent.com/15038803/42324878-1934e792-8082-11e8-9bfc-c50603b15b39.png">

**Step: 2**
Add this function in **`Keylogger.swift`**
```
func unscheduleHIDLoop()
{
    IOHIDManagerUnscheduleFromRunLoop( manager, CFRunLoopGetMain(), CFRunLoopMode.defaultMode.rawValue);
}
```
It should look like
<img width="961" alt="screen_shot_2018-07-05_at_6_35_56_pm" src="https://user-images.githubusercontent.com/15038803/42324952-681c45da-8082-11e8-936a-716592e97ad6.png">

**Step: 3**
Call it from your **`ViewController.swift`**
-> Create a static keylogger instance. Because you can keep using this object without creating a new one every time you check the box.
-> Call the `scheduleHIDLoop()` on the keylogger instance to start the keylogger.
-> Call the `unscheduleHIDLoop()` on the keylogger instance to stop the keylogger.
<img width="980" alt="screen_shot_2018-07-05_at_6_38_39_pm" src="https://user-images.githubusercontent.com/15038803/42325203-2400c640-8083-11e8-91f2-8848b1784d30.png">

**Step: 4**
To be able to run the keylogger correctly, you have make some changes to the permissions in your Xcode project.

There are 2 options.

1. Disable the app sandbox.
2. If you want to enable the app sandbox, then add this entitlements 
```com.apple.security.device.usb = YES```

**Comment by DamonGG** [comment]
I follow your details guides, and run it successful!

I don't know how to express my gratitude. Please accept my sincere thanks.
For you, may take up your precious time of one hour to answer such my "stupid question", but are saved to me several days, and I learned a lot of things, not just code, and the spirit of helping others. 

The world is so big, but only you have created such a good project and helped me, I'm glad I met such a good programmer as you.

This is a short story about a programmer helping another fresh programmer, but it has become a precious experience in my career. Thank you again, my friend @SkrewEverything .

**Comment by SkrewEverything** [comment]
@DamonGG Nice to hear. 

If you are capable of donating, then make a donation to support me to develop it further. So, that you can also make a contribution in helping fellow programmers.
