### ISSUE TITLE
CPM counter

### ISSUE THREAD

**Issue by wmertens** [SkrewEverything/Swift-Keylogger#15]
would be neat if this could be used to track your typing skills:

* cpm counter for a-z, 0-9 and symbols separately
* wpm counter based on spacebar
* accuracy based on backspace use

**Comment by SkrewEverything** [comment]
@wmertens The idea of this project is to build a sophisticated Keylogger but not a typing skills project.

Anyone interested can just fork this repo and build that project on top of Keylogger. It is not that hard to build it though. Just play with the `CallBackFunctions.swift` (where it saves the keys to file).

If you want any help regarding that, feel free to ask.

**Comment by wmertens** [comment]
I tried building, but it complains it can't open the HID when I run it :(

**Comment by SkrewEverything** [comment]
@wmertens That is strange. I have never encountered that error before. And apple documentation just mentioned about the possibility of that error but didn't mention any possible reasons for that though.

I have downloaded the project and ran in the Xcode. It runs fine.

So, can you try and answer these?
1. Did you build and ran the project in Xcode after downloading the repo without changing it? If you changed anything, can you please say which lines you have edited/changed so that I can reproduce the error on my machine?

2. Try to disconnect all the devices(maybe problem occurring due to other devices) and then try again with clean build project in Xcode.

3. Try to shutdown(all the applications closed) and start your mac(also disconnect all external devices) and then try again with clean build project in Xcode.

4. If all of them fail, try to download the binary from Releases Tab and run it once. Believe me the binary is safe and I didn't try to include any malware in that.

If all these fail(lets hope not), then I can't solve it because neither I nor others have never encountered this problem.

**Comment by boltronic** [comment]
Strangely, I'm having the same prob with openHIDManager! Looking through the code but haven't made any progress

*Edit: I'll try what you mentioned above, thanks!

**Comment by SkrewEverything** [comment]
@wmertens @boltronic Any update? Did it work?

**Comment by ayush169** [comment]
This is not working

**Comment by ayush169** [comment]
How to hide it from the taskbar?

**Comment by SkrewEverything** [comment]
@ayush169 Unless you are gonna post screenshots or explain it properly, I have no interest in helping people who can't even ask questions properly or get back to me with a proper update.

And honestly what does your question/issue has to do with the **CPM counter** issue? 

And here is a fun fact: I'm not a support girl/guy to ask you each and every question and walk you through the issue. Show some respect and effort before asking vague one-sentence questions. I don't have all day to keep asking you questions and waiting for your answers.

Want a proper and decent answer? Try to explain your issue in a new/old issue according to your existing issue with a detailed steps about what you did along with a proper error message or screenshots and explain what you want or expecting clearly.

I'm happy to walk you through the solution/answer but I'm not gonna do that for knowing what is your issue. If you can't even explain your issue properly I may have to visit your house to fix the problem because you are not gonna understand the solution/answer written here.

So, if you want a solution? Show some effort to explain it properly.

Sorry but not sorry...

Peace ✌🏻
