### ISSUE TITLE
Possibility to temporary enable/disable password log?

### ISSUE THREAD

**Issue by andreddie81** [SkrewEverything/Swift-Keylogger#16]
Hi,

Would it be possible to add the functionality to temporary enable/disable (self-disable) password log after certain given time?.

I have been having a look at your code but my Swift level is not the best.

Thanks.

**Comment by SkrewEverything** [comment]
Yes, it is possible. 

Take a look at this example in Readme: https://github.com/SkrewEverything/Swift-Keylogger#example-of-viewcontrollerswift

In that example, the keylogger can be stopped or started with the press of a button. You can use that for your case. Instead of a button, use a timer to start or stop it.

Let me know if you need any help.

**Comment by Joshfindit** [comment]
Seems like a good opportunity for an OSX service as well: simply stop the service when you want it off, then start it again when you want it on.

**Comment by andreddie81** [comment]
Hi thanks for your comments, 

Maybe I have not expressed correctly what i was looking for. I was referring only to the ability of the keylogger to log passwords. I was wondering if this feature could be turned on and off, and if turned on, give it some kind of timer for auto-turn off. 

Right now seems like this feature is not supported, the keylogger does not log passwords typed in the terminal. I have been having a look at the swift code and playing around with `DisableSecureEventInput()` function, without any success. But as i mentioned above, my Swift is limited.

Thanks!

**Comment by unknowndomain** [comment]
You cannot disable secure event input from a different application than the one that started it.
