### ISSUE TITLE
Azerty Version ? 

### ISSUE THREAD

**Issue by shellbear** [SkrewEverything/Swift-Keylogger#2]
Hello I just would like to ask if its possible to add an AZERTY version of this keylogger ? And why not detect automaticatly the language and choose between AZERTY and QWERTY keyboard ? Thank you

**Comment by SkrewEverything** [comment]
@ShellBear it's possible to add AZERTY version. This keylogger is just a small module for my project. So, I didn't think much and did it according to my requirement. 

By the way, it's not that hard. Just replace the strings given in `keyMap` variable(The keys arrangement are different. Just map the keys to AZERTY by looking at both AZERTY and QWERTY) in `Keylogger.swift`

**Comment by zackva** [comment]
I'll take a look at this as part of the Hacktoberfest if you don't mind @SkrewEverything

**Comment by pkamb** [comment]
Two useful links for anyone who takes this on (Dvorak support as well, please!)

Using key constants (`kVK_ANSI_O`) rather than the raw values used currently (`map[18]`) 
https://stackoverflow.com/questions/3202629/where-can-i-find-a-list-of-mac-virtual-key-codes/16125341#16125341

Using a `createStringForKey(CGKeyCode keyCode)` function that will eliminate the need for the `keycode: outputString` lookup table + use the current system keyboard layout:
https://stackoverflow.com/questions/1918841/how-to-convert-ascii-character-to-cgkeycode

**Comment by SkrewEverything** [comment]
@zackva Go ahead
